[env:HoloCubic]
platform = espressif32@~6.4.0
board = esp32-s3-devkitc-1
framework = arduino

monitor_filters = esp32_exception_decoder
monitor_speed = 115200
;upload_port = COM5
upload_speed = 921600

debug_tool = esp-builtin
;debug_init_break = break setup ; 在setup()中设置断点，开了之后初始化会很卡
;build_type = debug
debug_speed = 20000 ; KHz。如果 CPU 80 MHz 运行，则 JTAG 频率的上限为 20 MHz；如果 CPU 以 160 MHz 或者 240 MHz，则上限为 26 MHz。

build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-mfix-esp32-psram-cache-strategy=memw
	;-D USE_DMA=0
	;-D CONFIG_DISABLE_HAL_LOCKS=1
	;-D CONFIG_ARDUHAL_LOG_COLORS=0
    -D CORE_DEBUG_LEVEL=3      ; 日志级别：2-WARN,3-INFO,4-DEBUG
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1	
	-D UART_LOG_PRINT_EN=0			;0的时候从USB输出【debug代码时候】，1的时候debug信息从串口输出【release代码时候】
	;-D USE_SD_MMC=1				;使能使用SM_MMC，屏蔽使用SPI
	-D DISABLE_ALL_LIBRARY_WARNINGS		;禁止TFT_eSPI库编译警告

board_build.flash_mode = qio
board_build.f_flash = 80000000L

board_build.psram_type = opi
board_build.boot=qio
board_build.arduino.memory_type=qio_opi

board_build.partitions = large_spiffs_16MB.csv
board_upload.flash_size = 16MB

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-mfix-esp32-psram-cache-strategy=memw	
	-D CORE_DEBUG_LEVEL=3      ; 日志级别：2-WARN,3-INFO,4-DEBUG
	-D DISABLE_ALL_LIBRARY_WARNINGS		;禁止TFT_eSPI库编译警告

board_build.flash_mode = qio
board_build.f_flash = 80000000L

board_build.psram_type = opi
board_build.boot=qio
board_build.arduino.memory_type=qio_opi

board_build.partitions = large_spiffs_16MB.csv
board_upload.flash_size = 16MB



